simple_blog/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	# path('', views.index, name='index'),
	path('', views.post_list, name='post_list'),
	# path('post/<int:pk>/', views.post_detail, name='post_detail'),
	path('post/<int:pk>/<post_slug>/', views.post_detail, name='post_detail'),
	path('category/<category_slug>/', views.posts_by_category, name='posts_by_category'),
	path('tag/<tag_slug>/', views.posts_by_tag, name='posts_by_tag'),
	path('author/<author_slug>/', views.posts_by_author, name='posts_by_author'),
	path('blog/', views.test_redirect, name='test_redirect'),
	path('feedback/', views.feedback, name='feedback'),
	path('signup/', views.signup, name='signup'),
	path('track/', views.track_user, name='track_user'),
	path('stop-tracking/', views.stop_tracking, name='stop_tracking'),
	path('test-session/', views.test_session, name='test_session'),
	path('test-delete/', views.test_delete, name='test_delete'),
	path('save-session-data/', views.save_session_data, name='save_session_data'),
	path('access-session-data/', views.access_session_data, name='access_session_data'),
	path('delete-session-data/', views.delete_session_data, name='delete_session_data'),
	path('lousy-login/', views.lousy_login, name='lousy_login'),
	path('lousy-logged-inX/', views.lousy_logged_in, name='lousy_logged_in'),
	path('lousy-logout/', views.lousy_logout, name='lousy_logout'),
	path('login/', views.login, name='login'),
	path('admin_page/', views.admin_page, name='admin_page'),
	path('logout/', views.logout, name='logout'),

]

simple_blog/cadmin/urls.py
from django.urls import path, include
from . import views
from blog import views as blog_views
from django.contrib.auth import views as auth_views


app_name = 'cadmin'

urlpatterns = [
	path('post/add/', views.post_add, name='post_add'),
	path('post/update/<int:pk>/', views.post_update, name='post_update'),
	
	path('login/',
		auth_views.login,
		{'template_name': 'cadmin/login.html'},
		name='login'
	),
	path('logout/',
		auth_views.logout,
		{'template_name': 'cadmin/logout.html'},
		name='logout'
	),
	path('', views.home, name='home'),
	path('password-change-done/',
		auth_views.password_change_done,
		name='password_change_done'
	),
	path('password-change/',
		auth_views.password_change, 
		{'post_change_redirect': 'password_change_done'},
		name='password_change'
	),
	path('register/', views.register, name='register'),
	
]

simple_blog/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('cadmin/', include('cadmin.urls')),

]

simple_blog/cadmin/models.py
from django.db import models

# Create your models here.

simple_blog/cadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse
from blog.forms import PostForm
from django.contrib import messages
from django.template.defaultfilters import slugify
from blog.models import Author, Tag, Category, Post
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm


def post_add(request):
	if request== 'POST':
		f = PostForm(request.POST)
		slug = slugify(request.POST['title'])
		if f.is_valid():
			r = f.save(commit=False)
			r.slug = slug
			l = len(Post.objects.filter(slug__startswith=slug))
			if l:
				slug = slugify(slug + ' ' + str(l))
				r.slug = slug
				r.save()
			else:
				r.save()
			f.save_m2m()
			messages.add_message(request, messages.INFO, 'Post added.')
			print()
			p = Post.objects.get(slug=slug)
			return redirect(reverse('blog:post_detail', args=[p.id, p.slug]))

	else:
		f = PostForm()
	return render(request, 'cadmin/post_add.html', {'form': f})


def post_update(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		f = PostForm(request.POST, instance=post)
		slug = slugify(request.POST['title'])
		if f.is_valid():
			r = f.save(commit=False)
			p = Post.objects.filter(slug__startswith=slug)
			if post not in p:
				if not len(p):
					r.slug = slug
				else:
					r.slug = slug + '-{}'.format(len(p))
			r.save()
			f.save_m2m()
			messages.add_message(request, messages.INFO, 'Post updated.')
			return redirect(reverse('blog:post_detail', kwargs={'pk':post.id, 'post_slug': post.slug}))

	else:
		f = PostForm(instance=post)
	return render(request, 'cadmin/post_update.html', {'form': f, 'post': post})


def home(request):
	return render(request, 'cadmin/admin_page.html')

def login(request, **kwargs):
	if request.user.is_authenticated:
		return redirect('cadmin:home')
	return auth_views.login(request, **kwargs)

def logout(request, **kwargs):
	return auth_views.logout(request, **kwargs)

def register(request):
	if request.method == 'POST':
		f = UserCreationForm(request.POST)
		if f.is_valid():
			f.save()
			messages.success(request, "Account created successfully")
			return redirect('cadmin:register')
	else:
		f = UserCreationForm()
	return render(request, 'cadmin/register.html', {'form': f})

simple_blog/cadmin/templates/cadmin/admin_page.html
{% extends "blog/base.html" %}

{% block title %}Session Login - {{block.super}}{% endblock %}

{% block content %}
	<div class="content">
		<div class="section-inner clearfix">
			<h6>Hi, {{ request.user.get_full_name }}</h6>
			<p>User Details::</p>
			<ul>
				<li>Email: {{ request.user.email }}</li>
				<li>SuperUser: {{ request.user.is_superuser }}</li>
				<li>Staff: {{ request.user.is_staff }}</li>
				<li>Date Joined: {{ request.user.date_joined }}</li>
				<li>Last login: {{ request.user.last_login }}</li>
			</ul>
			<p><a href="{% url 'cadmin:logout' %}">Logout</a></p>
		</div>
	</div>
{% endblock %}

simple_blog/cadmin/templates/cadmin/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}

	<meta charset="UTF-8">
	<meta  name="viewport" content="width=device-width initial-scale=1.0">
	<title>{% block title %}The Great Django Blog :: Admin Panel{% endblock %}</title>
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static '/cadmin/css/style.css' %}">
</head>
<body>

	{% block content %}

	{% endblock %}

	<div class="footer">
        <div class="section-inner clearfix">
            <p>&copy; The Great Django Blog</p>
        </div>
    </div>
	

</body>
</html>

simple_blog/cadmin/templates/cadmin/base_admin.html
{% extends "cadmin/base.html" %}

{% block content %}

<div class="header">
	<div class="section-inner clearfix">
		<h2 class="title">Edit or Create Post</h2>
		<div class="user-welcome">
			<p>| {{ request.user }}</p>
		</div>
	</div>
</div>

		<!--<div class="sidebar">
			<ul>
				<li><a href="{% url 'blog:post_list' %}">Post</a></li>
				<li><a href="">Category</a></li>
				<li><a href="">Tag</a></li>
				<li><a href="">Account Info</a></li>
				<li><a href="">Change Password</a></li>
				<li><a target="_blank" href="">View Site</a></li>
				<li><a href="">Logout</a></li>
			</ul>
		</div>-->

		{% block main %}

		{% endblock %}
{% endblock %}

simple_blog/cadmin/templates/cadmin/login.html
{% extends "blog/base.html" %}

{% block title %}Login - {{block.super}}{% endblock %}

{% block content %}
	<div align="center">
			<h3>Login form</h3>
			{% if messages %}
				<ul style="color: red">
				{% for message in messages %}
					<li>{{message}}</li>
				{% endfor %}
				</ul>
			{% endif %}

			<form action="" method="post">
				{% csrf_token %}
				<table>
					<tr>
						<td><input type="text" name="username" id="id_username" placeholder="username"></td>
					</tr>

					<tr>
						<td><input type="password" name="password" id="id_password" placeholder="password"></td>
					</tr>
					<tr>
						<td><input type="hidden" name="next" value="{{ next|default:'/cadmin/' }}"></td>
					</tr>
					<tr>
						<td><input type="submit" name="submit" value="Submit"></td>
					</tr>
				</table>
			</form>
	</div>
{% endblock %}

simple_blog/cadmin/templates/cadmin/logout.html
{% extends "blog/base.html" %}

{% block title %}Session Login - {{block.super}}{% endblock %}

{% block content %}
	<div class="content">
		<div class="section-inner clearfix">
			<p>You are logged out ... <a href="{% url 'cadmin:login' %}">Login</a> again</p>
			
		</div>
	</div>
{% endblock %}

simple_blog/cadmin/templates/cadmin/post_add.html
{% extends "cadmin/base_admin.html" %}

{% block title %}
	Add new post - {{ block.super }}
{% endblock %}

{% block main %}

	<p>&#187; <a href="/">All Posts</a> &#187; Add Post</p>
	<h3>Add Post</h3>
	<ul>
		{% if messages %}
			{% for message in messages %}
				<b style="color: green">{{ message }}</b>
			{% endfor %}
		{% endif %}
	</ul>


	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<tr>
				<td></td>
				<td><input type="submit" name=""></td>
			</tr>
		</table>
	</form>

{% endblock %}

simple_blog/cadmin/templates/cadmin/post_update.html
{% extends "cadmin/base_admin.html" %}

{% block title %}
	Update Post - {{ block.super }}
{% endblock %}

{% block main %}
		<p>&#187; <a href="/">All Posts</a> &#187; Post Update</p>
		<h3>Post Update</h3>
		{% if messages %}
			<ul>
				{% for message in messages %}
					<b style="color: green">{{ message }}</b>
				{% endfor %}
			</ul>
		{% endif %}

		<form action="" method="post">
			{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td></td>
					<td><input type="submit" name="" value="Update Post"></td>
				</tr>
			</table>
		</form>
{% endblock %}

simple_blog/cadmin/templates/cadmin/register.html
{% extends "cadmin/base.html" %}

{% block title %}Create User - {{ block.super }}
{% endblock %}

{% block content %}

<div class="login">
	{% if messages %}
		<ul>
		{% for message in messages %}
			<li style="color: red">{{ message }}</li>
		{% endfor %}
		</ul>
	{% endif %}
	<h1>Create Account </h1>
	<form method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<tr>
				<td></td>
				<td><input type="submit" name="submit" value="Register"></td>
			</tr>
		</table>
	</form>
</div>
{% endblock %}