simple_blog/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	# path('', views.index, name='index'),
	path('', views.post_list, name='post_list'),
	# path('post/<int:pk>/', views.post_detail, name='post_detail'),
	path('post/<int:pk>/<post_slug>/', views.post_detail, name='post_detail'),
	path('category/<category_slug>/', views.posts_by_category, name='posts_by_category'),
	path('tag/<tag_slug>/', views.posts_by_tag, name='posts_by_tag'),
	path('author/<author_slug>/', views.posts_by_author, name='posts_by_author'),
	path('blog/', views.test_redirect, name='test_redirect'),
	path('feedback/', views.feedback, name='feedback'),
	path('signup/', views.signup, name='signup'),
	path('track/', views.track_user, name='track_user'),
	path('stop-tracking/', views.stop_tracking, name='stop_tracking'),
	path('test-session/', views.test_session, name='test_session'),
	path('test-delete/', views.test_delete, name='test_delete'),
	path('save-session-data/', views.save_session_data, name='save_session_data'),
	path('access-session-data/', views.access_session_data, name='access_session_data'),
	path('delete-session-data/', views.delete_session_data, name='delete_session_data'),
	path('lousy-login/', views.lousy_login, name='lousy_login'),
	path('lousy-logged-inX/', views.lousy_logged_in, name='lousy_logged_in'),
	path('lousy-logout/', views.lousy_logout, name='lousy_logout'),
	path('login/', views.login, name='login'),
	path('admin_page/', views.admin_page, name='admin_page'),
	path('logout/', views.logout, name='logout'),

]

simple_blog/cadmin/urls.py
from django.urls import path, include
from . import views
from blog import views as blog_views
from django.contrib.auth import views as auth_views


app_name = 'cadmin'

urlpatterns = [
	path('post/add/', views.post_add, name='post_add'),
	path('post/update/<int:pk>/', views.post_update, name='post_update'),
	
	path('login/',
		auth_views.login,
		{'template_name': 'cadmin/login.html'},
		name='login'
	),
	path('logout/',
		auth_views.logout,
		{'template_name': 'cadmin/logout.html'},
		name='logout'
	),
	path('', views.home, name='home'),
	path('password-change-done/',
		auth_views.password_change_done,
		name='password_change_done'
	),
	path('password-change/',
		auth_views.password_change, 
		{'post_change_redirect': 'password_change_done'},
		name='password_change'
	),
	path('register/', views.register, name='register'),
	
]

simple_blog/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('cadmin/', include('cadmin.urls')),

]

simple_blog/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
# Create your models here.


class Author(models.Model):
	name = models.CharField(max_length=50, unique=True, verbose_name='Author Name')
	# slug = models.SlugField(max_length=100, default='author_slug', unique=False)
	email = models.EmailField(unique=True, verbose_name='Author Email')
	active = models.BooleanField(default=True)
	created_on = models.DateTimeField(auto_now_add=True)
	last_logged_in = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name + ' : ' + self.email

	def get_absolute_url(self):
		# return '/author/{0}/'.format(self.name)
		return reverse('blog:posts_by_author', args=[self.name])


class Category(models.Model):
	name = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		# return '/category/{0}/'.format(self.slug)
		return reverse('blog:posts_by_category', args=[self.slug])

	class Meta:
		verbose_name_plural = 'Categories'


class Tag(models.Model):
	name = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		# return '/tag/{0}/'.format(self.slug)
		return reverse('blog:posts_by_tag', args=[self.slug])


class Post(models.Model):
	title = models.CharField(max_length=200)
	slug = models.SlugField(unique=True, help_text='Slug field will be generated automatically from the title of the post')
	content = models.TextField()
	pub_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	tags = models.ManyToManyField(Tag)

	def __str__(self):
		return self.title

	# def save(self, *args, **kwargs):
	# 	self.slug = slugify(self.title)
	# 	super(Post, self).save(*args, **kwargs)

	def get_absolute_url(self):
		# return '/post/{0}/'.format(self.id)
		return reverse('blog:post_detail', args=[self.id, self.slug,])


class Feedback(models.Model):
	name = models.CharField(max_length=200, help_text='Name of the sender')
	email = models.EmailField(max_length=200)
	subject = models.CharField(max_length=200)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name + ' -> ' + self.email

simple_blog/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from .models import Author, Category, Tag, Post, Feedback
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = '__all__'

	def clean_name(self):
		name = self.cleaned_data['name'].lower()
		if name in ['author', 'admin']:
			raise ValidationError("Author name can't be 'author/admin' ")
		return name

	def clean_email(self):
		return self.cleaned_data['email'].lower()


class TagForm(forms.ModelForm):
	class Meta:
		model = Tag
		fields = '__all__'

	def clean_name(self):
		t = self.cleaned_data['name'].lower()
		if t in ('tag', 'add', 'update'):
			raise ValidationError("Tag name can't be {0}".format(t))
		return t

	def clean_slug(self):
		return self.cleaned_data['slug'].lower()


class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = '__all__'

	def clean_name(self):
		c = self.cleaned_data['name'].lower()
		if c in ('category', 'add', 'update'):
			raise ValidationError("Category name can't be {0}".format(c))
		return c

	def clean_slug(self):
		return self.cleaned_data['slug'].lower()


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'content', 'author', 'category', 'tags')

	def clean_title(self):
		t = self.cleaned_data['title'].lower()
		if t in ('post', 'add', 'update', 'remove'):
			raise ValidationError("Post title can't be \"{0}\"".format(t))
		return t

	# def clean(self):
	# 	cleaned_data = super(PostForm, self).clean()
	# 	title = cleaned_data.get('title')
	# 	l = len(Post.objects.filter(slug__startswith=slugify(title)))
	# 	if title:
	# 		if l:
	# 			cleaned_data['slug'] = slugify(title) + '-{}'.format(l+5)
	# 		else:
	# 			cleaned_data['slug'] = slugify(title)
	# 	return cleaned_data


class FeedbackForm(forms.ModelForm):
	class Meta:
		model = Feedback
		fields = '__all__'


class SignUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

simple_blog/blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
import datetime
from django import template
from .models import Author, Tag, Post, Category
from django.contrib import messages
from .forms import FeedbackForm, SignUpForm
from django.core.mail import mail_admins
from django_project import helpers
from django.contrib import auth


def index(request):
	return HttpResponse('Hello Django!')

# view function to display a list of all posts
def post_list(request):
	posts = Post.objects.order_by('-id').all()
	posts = helpers.pg_records(request, posts, 10)
	return render(request, 'blog/post_list.html', {'posts': posts})

# view function to diaplay a single post
def post_detail(request, pk, post_slug):

	# post = Post.objects.get(pk=pk)
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post': post})

# view function to display posts under a specific Category
def posts_by_category(request, category_slug):
	category = get_object_or_404(Category, slug=category_slug)
	posts = get_list_or_404(Post.objects.order_by('-id'), category=category)
	posts = helpers.pg_records(request, posts, 10)
	context = {
		'category': category,
		'posts': posts,
	}

	return render(request, 'blog/posts_by_category.html', context)

# view function to display posts under a specific Tag
def posts_by_tag(request, tag_slug):
	tag = get_object_or_404(Tag, slug=tag_slug)
	posts = get_list_or_404(Post.objects.order_by('-id'), tags=tag)
	posts = helpers.pg_records(request, posts, 10)
	context = {
		'tag': tag,
		'posts': posts,
	}
	
	return render(request, 'blog/posts_by_tag.html', context)

# view function to display posts under a specific Author
def posts_by_author(request, author_slug):
	author = get_object_or_404(Author, name=author_slug)
	posts = get_list_or_404(Post.objects.order_by('-id'), author=author)
	posts = helpers.pg_records(request, posts, 10)
	context = {
		'author': author,
		'posts': posts
	}

	return render(request, 'blog/posts_by_author.html', context)


def test_redirect(request):
	c = Category.objects.get(slug='python')
	return redirect(c, permanent=True)

def feedback(request):
	if request.method == 'POST':
		f = FeedbackForm(request.POST)
		if f.is_valid():
			name = f.cleaned_data['name']
			email = f.cleaned_data['email']
			subject = "You have a new Feedback from {}:{}".format(name, email)
			message = "Subject: {}\n\nMessage: {}\n\n".format(f.cleaned_data['subject'], f.cleaned_data['message'])
			f.save()
			mail_admins(subject, message)
			
			
			messages.add_message(request, messages.INFO, 'Feedback Submitted')
			return redirect('blog:feedback')

	else:
		f = FeedbackForm()
	return render(request, 'blog/feedback.html', {'form': f})


def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if f.is_valid():
			f.save()
			messages.add_message(request, messages.INFO, 'Account Created')
			return redirect('blog:signup')
	else:
		form = SignUpForm()
	return render(request, 'blog/signup.html', {'form': form})


def track_user(request):
	response = render(request, 'blog/track_user.html')
	if not request.COOKIES.get('count'):
		response.set_cookie('count', '1', 3600 * 24 * 365 * 2)
	else:
		count = str(int(request.COOKIES.get('count')) + 1)
		response.set_cookie('count', count, 3600 * 24 * 365 * 2)
	return response

def stop_tracking(request):
	if request.COOKIES.get('count'):
		response = HttpResponse('Cookies cleared')
		response.delete_cookie('count')
	else:
		response = HttpResponse('We are no longer tracking you')
	return response

def test_session(request):
	request.session.set_test_cookie()
	return HttpResponse('Testing session cookie')

def test_delete(request):
	if request.session.test_cookie_worked():
		request.session.delete_test_cookie()
		response = HttpResponse('Cookie test passed')
	else:
		response = HttpResponse('Cookie test failed !')
	return response

def save_session_data(request):
	request.session['id'] = 1
	request.session['name'] = 'Bijoy'
	request.session['password'] = 'hotpass'
	return HttpResponse("Session data saved")

def access_session_data(request):
	response = ''

	if request.session.get('id'):
		response += 'Id: {0} <br>'.format(request.session.get('id'))

	if request.session.get('name'):
		response += 'Name: {0} <br>'.format(request.session.get('name'))

	if request.session.get('password'):
		response += 'password: {0} <br>'.format(request.session.get('password'))

	if not response:
		return HttpResponse('No session data')
	else:
		return HttpResponse(response)

def delete_session_data(request):
	try:
		del request.session['id']
		del request.session['name']		
		del request.session['password']
	except KeyError:
		pass

	return HttpResponse("session data cleared")

def lousy_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		if username == 'root' and password == 'pass':
			request.session['logged_in'] = True
			return redirect('blog:lousy_logged_in')
		else:
			messages.error(request, 'Wrong username/password')
			return redirect('blog:lousy_logged_in')
	else:
		if request.session.get('logged_in'):
			return redirect('blog:lousy_logged_in')
		return render(request, 'blog/lousy_login.html')

def lousy_logged_in(request):
	if not request.session.get('logged_in'):
		return redirect('blog:lousy_login')
	return render(request, 'blog/lousy_logged_in.html')

def lousy_logout(request):
	if request.session['logged_in']:
		request.session['logged_in'] = False
		return render(request, 'blog/lousy_logout.html')
	return redirect('blog:lousy_login')

def login(request):
	if request.user.is_authenticated:
		return redirect('blog:admin_page')
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = auth.authenticate(username=username, password=password)

		if user:
			auth.login(request, user)
			return redirect('blog:admin_page')
		else:
			messages.error(request, 'Error wrong username/password')
	return render(request, 'blog/login.html')

def admin_page(request):
	if not request.user.is_authenticated:
		return redirect('blog:login')
	return render(request, 'blog/admin_page.html')

def logout(request):
	auth.logout(request)
	return render(request, 'blog/logout.html')

simple_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}The Great Django Blog{% endblock %}</title>
	<meta  name="viewport" content="width=device-width initial-scale=1.0">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
	<script type="text/javascript" src="{% static 'blog/js/jquery.js' %}"></script>
</head>
<body>
	<center>
		<table bgcolor="#f6f6ef">
	<tr>
	<td>
	<div class="navbar">
		<div class="section-inner clearfix">
			<nav>
				<a href="/">BLog</a> |
				<a href="/cadmin/post/add"><b>Add Post</b></a> |
                <!--<a href="/feedback/">Contact Us</a> | -->
                <a href="/signup/">Register</a> |
                <a href="#" style="color: red">{{ request.user }}</a>
                
			</nav>
		</div>
	</div>
</td>
	</tr>
	<tr>
		<td>
	{% block content %}

	{% endblock %}
</td>
</tr>
<tr><td>
	{% block footer %}

	<div class="footer">
		<div class="section-inner clearfix">
			<hr>
			<p>&copy; The Great Django footer</p>
		</div>
	</div>

	{% endblock %}
</td></tr>
</table>
</center>
</body>
</html>

simple_blog/blog/templates/blog/datetime.html
{% extends "base.html" %}

{% block title %}Date and Time of today {% endblock %}

{% block content %}

	{# this is one line comment #}
	{% if now %}
		<p>Current date and time is {{ now }}</p>
	{% else %}
		<p>Now variable is not available</p>
	{% endif %}

	<p>Current scheme: <b> {{ request.scheme }}</b></p>
	<p>BASE_DIR: <b>{{ base_dir }}</b></p>

{% endblock %}

{% block footer %}
<p>All rights reseverd!</p>
{{ block.super }}
{% endblock %}

simple_blog/blog/templates/blog/feedback.html
{% extends "blog/base.html" %}

{% block title %}Feedback - {{ block.super }} {% endblock %}

{% block content %}
	{% if messages %}
	<ul>
		{% for message in messages %}
			<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<div class="content">
    	<div class="section-inner clearfix">
    		<h3>Submit Your Erotic Feedback</h3>
			<form action="" method="post">
				{% csrf_token %}
				<table>
					<!-- {{ form.as_table }} -->
					<tr>
						<td>
							{{ form.name.errors }}
							<input type="text" name="name" placeholder="{{ form.name.label }}" required>
						</td>
					</tr>

					<tr>
						<td>
							{{ form.email.errors }}
							<input type="email" name="email" placeholder="Email" required>
						</td>
					</tr>

					<tr>
						<td>
							{{ form.subject.errors }}
							<textarea name="subject" rows="3" cols="30" placeholder="Subject" required></textarea>
						</td>
					</tr>

					<tr>
						<td>
							{{ form.message.errors }}
							<textarea name="message" rows="10" cols="50" placeholder="Write your message..." required></textarea>
						</td>
					</tr>

					<tr>
						<td><input type="submit" name="" value="Submit"></td>
					</tr>
				</table>
			</form>
		</div>
	</div>

{% endblock %}

simple_blog/blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block title %}Login - {{block.super}}{% endblock %}

{% block content %}
	<div align="center">
			<h3>Login form</h3>
			{% if messages %}
				<ul style="color: red">
				{% for message in messages %}
					<li>{{message}}</li>
				{% endfor %}
				</ul>
			{% endif %}

			<form action="" method="post">
				{% csrf_token %}
				<table>
					<tr>
						<td><input type="text" name="username" id="id_username" placeholder="username"></td>
					</tr>

					<tr>
						<td><input type="password" name="password" id="id_password" placeholder="password"></td>
					</tr>

					<tr>
						<td><input type="submit" name="submit" value="Submit"></td>
					</tr>
				</table>
			</form>
	</div>
{% endblock %}

simple_blog/blog/templates/blog/lousy_logged_in.html
{% extends "blog/base.html" %}


{% block content %}
	<p>You are logged in !!! . <a href="{% url 'blog:lousy_logout' %}">logout</a></p>
{% endblock %}

simple_blog/blog/templates/blog/lousy_logout.html
{% extends "blog/base.html" %}

{% block content %}
	<p>You are logged out ! <a href="{% url 'blog:lousy_login' %}">Login</a></p>
{% endblock %}

simple_blog/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block title %}
	{{ post.title|capfirst }} - {{ block.super }}
{% endblock %}


{% block content %}

	<div class="content">
		<div class="section-inner clearfix">
			{% if messages %}
			<ul>
				{% for message in messages %}
					<li style="color: green">{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}

			<h1><b style="color: green">{{ post.title|capfirst }}</b></h1>

			<p class="post-info">
				{% include 'blog/post_info.html' %}
			</p>

			<p>
				{{ post.content }}
			</p>

		</div>
	</div>

{% endblock %} 

simple_blog/blog/templates/blog/post_info.html
<span><b>Date: {{ post.pub_date }}</b></span> |
<span><b>Category: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></b></span> |
<span><b>Tag:

	{% for tag in post.tags.all %}
		<a href="{{ tag.get_absolute_url }}">{{ tag }}</a>
	{% empty %}
		None
	{% endfor %}
</b>
</span> |
<span><b>Author: <a href="{{ post.author.get_absolute_url }}">{{ post.author.name }}</a></b></span>

 {% if request.user.is_authenticated and request.user.username == post.author.name %}|<span><b><a href="{% url 'cadmin:post_update' post.id %}">Edit</a></b></span>
 {% endif %}

simple_blog/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}
	Blogg - {{ block.super }}
{% endblock %}


{% block content %}

	<div class="content">
		<div class="section-inner clearfix">
			
			{% for post in posts %}
				<h3>
					<a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
				</h3>
				<p class="post-info">
					{% include 'blog/post_info.html' %}
				</p>

			{% empty %}
				<P>There is no posts</P>
			{% endfor %}


		</div>
	</div>

	{% include "blog/pagination.html" %}

{% endblock %}

simple_blog/blog/templates/blog/posts_by_author.html
{% extends "blog/base.html" %}

{% block title %}
	{{ block.super }} - {{ author.name }}
{% endblock %}


{% block content %}

	<div class="content">
		<div class="section-inner clearfix">
			
			<h4>All Posts of Author - {{ author.name }}</h4>

			{% for post in posts %}
				<h3>
					<a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
				</h3>
				<p class="post-info">
					{% include 'blog/post_info.html' %}
				</p>

			{% empty %}
				<P>There is no posts</P>
			{% endfor %}


		</div>
	</div>

	{% include "blog/pagination.html" %} 

{% endblock %}

simple_blog/blog/templates/blog/posts_by_category.html
{% extends "blog/base.html" %}

{% block title %}
	{{ block.super }} - {{ category.name }}
{% endblock %}

{% block content %}
	
	<div class="content">
		<div class="section-inner clearfix">
		
			<h4>All Posts Under category - {{ category.name }}</h4>
			
			{% for post in posts %}
				<h3>
					<a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
				</h3>
				<p class="post-info">
					{% include 'blog/post_info.html' %}
				</p>

			{% empty %}
				<P>There is no posts</P>
			{% endfor %}


		</div>
	</div>

	{% include "blog/pagination.html" %}
		
	</div>

{% endblock %}

simple_blog/blog/templates/blog/posts_by_tag.html
{% extends "blog/base.html" %}

{% block title %}
	{{ block.super }} - {{ tag.name }}
{% endblock %}

{% block content %}
	
	<div class="content">
		<div class="section-inner clearfix">
		
			<h4>All Posts Under tag - {{ tag.name }}</h4>
			
			{% for post in posts %}
				<h3>
					<a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
				</h3>
				<p class="post-info">
					{% include 'blog/post_info.html' %}
				</p>

			{% empty %}
				<P>There is no posts</P>
			{% endfor %}


		</div>
	</div>

	{% include "blog/pagination.html" %}

{% endblock %}

simple_blog/blog/templates/blog/signup.html
{% extends "blog/base.html" %}

{% block title %}Sign Up - {{ block.super }}{% endblock %}

{% block content %}
<div align="center">
	{% for message in messages %}
	<b style="color: green">{{ message }}</b>
	{% endfor %}
	<h3>Sign Up</h3>
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<tr>
				<td></td>
				<td><input type="submit" name="" value="SignUp"></td>
			</tr>
		</table>
	</form>
</div>
{% endblock %}

simple_blog/blog/templates/blog/time.html
<b><p style="color: green">Current date and time is: {{ now }}</p></b>